server:
  port: ${PORT:8080}
  tomcat:
    max-http-form-post-size: 10MB

spring:
  application:
    name: blog-website
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  web:
    resources:
      static-locations: classpath:/static/

  servlet:
    multipart:
      max-request-size: 10MB

  profiles:
    active: secret
cloudinary:
  cloud-name: ${CLOUDINARY_NAME}
  api-key: ${CLOUDINARY_KEY}
  api-secret: ${CLOUDINARY_SECRET}
jwt:
  signerKey: "b61be1b79d764b64a74332525cc9d1100c44011194a31cb568a3a297a990b406"